apiVersion: v2
name: network
description: A Helm chart for Kubernetes that will support a networking layer of the homelab.

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: traefik
    version: 38.0.2
    repository: "https://traefik.github.io/charts"
  - name: cloudflare-tunnel
    version: 0.1.0
    repository: "file://charts/cloudflared"
